apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-team-memory
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9111
      protocol: TCP
  selector:
    app: team-memory
